name = "worker"
main = "src/index.ts"
compatibility_date = "2023-01-15"

[vars]
AIRTABLE_BASE_ID = "applHyeERVSTPbVmk"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "http://localhost:3000/contact"
AIRTABLE_API_KEY="keyaneqfbWSQLBl6a"  # DEV_ONLY. This line should be removed.
